apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureBlockConfigMapKeys
metadata:
  name: block-configmap-keys
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["ConfigMap"]
  parameters:
    restrictedKeys: {{ .Values.restrictedKeys }}
